********************************************************
*** EXTRAE LAS LLAMADAS DE LOS ARCHIVOS ABO Y LOS DEJA EN
*** UNA TABLA TEMPORARIA LLAMADA ".\TEMP\TMPLLAMADAS.DBF"
*** CAMINO = MISERVIDOR
********************************************************
FUNCTION BUSLLAMADA
PARAMETER ABO, P_DESDE, P_HASTA,P_LLAMADO, CAMINO

SET DECIMALS TO 4

if file(".\temp\TMPLLAMADAS.dbf") THEN
	if used("TMPLLAMADAS") then
		sele TMPLLAMADAS
		use
	endif
	DELETE FILE .\temp\TMPLLAMADAS.dbf
endif

CREATE TABLE .\TEMP\TMPLLAMADAS FREE (SECUENCIA N(4), TELEFONO C(4), SALIDA N(4), DIA N(2),BARRA C(1), MES N(2), ;
                                   HORA N(2),PUNTOS C(1), MINUTOS N(2), DURACION N(8), IMPORTE C(6), NLLAMA1 C(4), ;
                                   NLLAMA2 C(12), OTROS0 C(11),CLAVE C(2) ,OTROS C(11), PESOS N(10,4), FECHA D)


TIPO = ""
LLAMESD = MONTH(P_DESDE)
LLAMESH = MONTH(P_HASTA)
LLANIOD = YEAR(P_DESDE)
LLANIOH = YEAR(P_HASTA)
LLAMESES = LLAMESD
LLAANIOS = LLANIOD

PATHBUSQUEDA = ""
ANIOMES = ALLTRIM(STR(LLAANIOS))+SUBSTR(ALLTRIM(STR(LLAMESES+100)),2,2)
DO WHILE ANIOMES<=ALLTRIM(STR(LLANIOH))+SUBSTR(ALLTRIM(STR(LLAMESH+100)),2,2)

	PATHBUSQUEDA = ALLTRIM(CAMINO)+ALLTRIM(STR(LLAANIOS))+SUBSTR(ALLTRIM(STR(LLAMESES+100)),2,2)+"\"
	IF DIRECTORY(PATHBUSQUEDA) THEN 
		=LLAMADAS_01(PATHBUSQUEDA)
	** RETORNA EL ARCHIVO TLLAMADA CON LAS LLAMADAS DEL PERIODO, ENTRANTES Y SALIENTES
		SELECT TMPLLAMADAS
		APPEND FROM .\TEMP\TLLAMADA
	ENDIF 

	IF LLAMESES = 12  THEN 
		LLAMESES = 1
		LLAANIOS = LLAANIOS + 1
	ELSE 
		LLAMESES = LLAMESES + 1
	ENDIF 
	ANIOMES = ALLTRIM(STR(LLAANIOS))+SUBSTR(ALLTRIM(STR(LLAMESES+100)),2,2)
ENDDO 
** HASTA AQUI TENGO UNA GRAN TABLA CON TODAS LAS LLAMADAS DEL PERIODO SELECCIONADO **
** TANTO ENTRANTES COMO SALIENTES **
=LLAMADAS_02(ABO,P_DESDE, P_HASTA,P_LLAMADO)

SET DECIMALS TO 2
RETURN 

******************************************************************
******************************************************************
FUNCTION LLAMADAS_01
PARAMETERS PATHDIR

if file(".\temp\TLLAMADA.dbf") THEN
	if used("TLLAMADA") then
		sele TLLAMADA
		use
	endif
	DELETE FILE .\temp\TLLAMADA.dbf
endif

CREATE TABLE .\TEMP\TLLAMADA FREE (SECUENCIA N(4), TELEFONO C(4), SALIDA N(4), DIA N(2),BARRA C(1), MES N(2), ;
                                   HORA N(2),PUNTOS C(1), MINUTOS N(2), DURACION N(8), IMPORTE C(6), NLLAMA1 C(4), ;
                                   NLLAMA2 C(12),OTROS0 C(11),CLAVE C(2) ,OTROS C(11), PESOS N(10,4), FECHA D)

SET DEFAULT TO &PATHDIR
ARCHIVOS = ADIR(MARCHIVOS,'ABO*.*')
SET DEFAULT TO &MMIESTACION

SELE TLLAMADA
FOR I = 1 TO ARCHIVOS 
	IF !(SUBSTR(ALLTRIM(MARCHIVOS(I,1)),4,1) = "D") THEN 
		EJE = "APPEND FROM "+PATHDIR+ALLTRIM(MARCHIVOS(I,1))+" SDF"
		&EJE
	ENDIF 
ENDFOR 
GO TOP 
DELETE FOR IMPORTE = "...." OR MES < 1 OR MES > 12
REPLACE ALL FECHA WITH DATE(VAL(SUBSTR(PATHDIR,LEN(ALLTRIM(PATHDIR))-6,4)),IIF(MES <1 OR MES>12,VAL(SUBSTR(PATHDIR,LEN(ALLTRIM(PATHDIR))-2,2)),MES),DIA)
GO TOP
AN = 0
ACT = 0
DO WHILE !EOF()
	AN = ACT
	ACT = tllamada.secuencia	
	IF tllamada.secuencia = AN THEN
		delete
	ENDIF
	skip
ENDDO

RETURN 


******************************************************************
******************************************************************
FUNCTION LLAMADAS_02
PARAMETERS TELE, FD, FH, NL

CHARTELE = SUBSTR(ALLTRIM(STR(TELE)),3)

if file(".\temp\TLLAMADA02.dbf") THEN
	if used("TLLAMADA02") then
		sele TLLAMADA02
		use
	endif
	DELETE FILE .\temp\TLLAMADA02.dbf
endif

CREATE TABLE .\TEMP\TLLAMADA02 FREE (TELEFONO N(20),FECHA D, HORA C(5), ;
									DURACION N(10), IMPORTE N(10,4), NRODISCA C(16),CLAVE C(2), ES N(1))

IF !(TELE=0) THEN  && SI TELEFONO NO ES 0 O SEA QUE SE ESPECIFICO PARA UN TELEFONO PARTICULAR

	** TODAS LAS LLAMADAS ENTRANTES TLLAMA02E DE LARGA DISTANCIA
	SELECT INT(VAL("49"+ALLTRIM(nllama1))) as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, 0.0000 as importe,  ;
		   SUBSTR(ALLTRIM(nllama2),2) as nrodisca, ;
		   "  " as clave, ;
		   1 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02E ;
	WHERE (ALLTRIM(IMPORTE)=="INDEFI") AND (ALLTRIM(nllama1)== ALLTRIM(chartele)) ;
		  AND (fecha between FD AND FH )

	** TODAS LAS LLAMADAS SALIENTES DESDE EL TELEFONO ELEGIDO TLLAMA02S
	SELECT INT(VAL("49"+SUBSTR(ALLTRIM(telefono),1,10))) as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, VAL(importe) as importe,  ;
		   ALLTRIM(nllama1)+ALLTRIM(nllama2) as nrodisca, ;
		   clave, ;
		   0 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02S ;
	WHERE ALLTRIM(telefono)==ALLTRIM(chartele)  AND (fecha between FD AND FH )

	** TODAS LAS LLAMADAS ENTRANTES DESDE TELEFONOS DE MARGARITA AL TELEFONO ELEGIDO

	SELECT TELE as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, 0.0000 as importe,  ;
		   "49"+ALLTRIM(telefono) as nrodisca, ;
		   clave, ;
		   1 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02M ;
	WHERE  (ALLTRIM(nllama1)+ALLTRIM(nllama2) = "49"+ALLTRIM(CHARTELE) OR ;
			ALLTRIM(nllama1)+ALLTRIM(nllama2) = "0348349"+ALLTRIM(CHARTELE)) AND ;
			(fecha between FD AND FH )

	SELECT TLLAMADA02
	APPEND FROM .\TEMP\TLLAMA02E
	APPEND FROM .\TEMP\TLLAMA02S
	APPEND FROM .\TEMP\TLLAMA02M
	INDEX ON STR(TELEFONO)+DTOC(FECHA)+ALLTRIM(HORA) TAG ORDEN1

ELSE && SI TELEFONO ES 0 NO SE ESPECIFICO NINGUN TELEFONO EN PARTICULAR

	MESSAGEBOX("S1")

	** TODAS LAS LLAMADAS ENTRANTES TLLAMA02E DE LARGA DISTANCIA
	SELECT INT(VAL("49"+ALLTRIM(nllama1))) as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, 0.0000 as importe,  ;
		   SUBSTR(ALLTRIM(nllama2),2) as nrodisca, ;
		   "  " as clave, ;
		   1 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02E ;
	WHERE (ALLTRIM(IMPORTE)=="INDEFI")  ;
		  AND (fecha between FD AND FH )

	MESSAGEBOX("S2")

	** TODAS LAS LLAMADAS SALIENTES DESDE EL TELEFONO ELEGIDO TLLAMA02S
	SELECT INT(VAL("49"+STRTRAN(SUBSTR(ALLTRIM(telefono),1,10),'E','0'))) as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, VAL(importe) as importe,  ;
		   ALLTRIM(nllama1)+ALLTRIM(nllama2) as nrodisca, ;
		   clave, ;
		   0 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02S ;
	WHERE !(ALLTRIM(IMPORTE)=="INDEFI") AND (fecha between FD AND FH )

	** TODAS LAS LLAMADAS ENTRANTES DESDE TELEFONOS DE MARGARITA AL TELEFONO ELEGIDO
	MESSAGEBOX("S3")

	SELECT INT(VAL(SUBSTR((ALLTRIM(nllama1)+ALLTRIM(nllama2)),1,10))) as telefono, ;
		   FECHA, SUBSTR(ALLTRIM(str(hora+100)),2)+":"+SUBSTR(ALLTRIM(STR(minutos+100)),2) as hora, ;
		   duracion, 0.0000 as importe,  ;
		   "49"+ALLTRIM(telefono) as nrodisca, ;
		   clave, ;
		   1 AS ES ;
	FROM TMPLLAMADAS INTO TABLE .\TEMP\TLLAMA02M ;
	WHERE  (ALLTRIM(nllama1)+ALLTRIM(nllama2) = "49" OR ;
			ALLTRIM(nllama1)+ALLTRIM(nllama2) = "0348349") AND ;
			(fecha between FD AND FH )
	MESSAGEBOX("S4")
			
	SELECT TLLAMADA02
	APPEND FROM .\TEMP\TLLAMA02E
	APPEND FROM .\TEMP\TLLAMA02S
	APPEND FROM .\TEMP\TLLAMA02M
	INDEX ON STR(TELEFONO)+DTOC(FECHA)+ALLTRIM(HORA) TAG ORDEN1

ENDIF 

RETURN 