
FUNCTION LEECONFIG
PARAMETERS p_archivo
	IF TYPE('p_archivo') == 'C'
			PUNTERO = FOPEN("config\"+ALLTRIM(p_archivo),0)
		IF PUNTERO > 0 THEN
			DO WHILE !FEOF(PUNTERO)
				EJE = ALLTRIM(FGETS(PUNTERO))
				IF !((ALLTRIM(EJE) == "") OR (SUBSTR(ALLTRIM(EJE),1,1)=="[")) THEN
					&EJE
				ENDIF
			ENDDO
			=FCLOSE(PUNTERO)
			SET SAFETY OFF
		ENDIF
	
	ENDIF 

RETURN
