* MUESTRA LAS PESADAS QUE SE HICIERON POR CADA OT
SELECT O.IDOT,O.cantsoli,O.cantfactu,O.kgfactu,O.PROPIEDAD,O.NOMPROP,O.CODVALOR,O.NOMVALOR,O.COLOR,;
       O.NOMCOLOR,O.NROOTCLIEN,O.CODIGOART,O.NOMBREART,count(P.nropaquete), ;
       SUM(P.CANTIDAD) AS CANTIDAD,SUM(P.PESOREAL) AS PESOREAL ;
   FROM OT O, PESADAH P WHERE O.IDOT=P.IDOT GROUP BY O.IDOT